"""Add show_slider, is_featured, slider_photos

Revision ID: 07aaeade1f46
Revises: e969af6d25af
Create Date: 2026-09-16 20:26:46.792882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07aaeade1f46'
down_revision = 'e969af6d25af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_slider', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('show_slider')

    # ### end Alembic commands ###
