"""Add quota_bytes to User

Revision ID: 2acf88b0c238
Revises: 09615f7884d8
Create Date: 2026-09-26 17:23:46.662792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2acf88b0c238'
down_revision = '09615f7884d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'quota_bytes',
            sa.BigInteger(),
            nullable=False,
            server_default='1073741824',   # 1 ГБ для существующих пользователей
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('quota_bytes')

    # ### end Alembic commands ###
