"""Add slider_delay_seconds

Revision ID: 923fa274a375
Revises: 07aaeade1f46
Create Date: 2026-09-17 18:25:03.547829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923fa274a375'
down_revision = '07aaeade1f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slider_photos')
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slider_delay_seconds', sa.Integer(), nullable=False, server_default='5'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('slider_delay_seconds')

    op.create_table('slider_photos',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('settings_id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_file.id'], ),
    sa.ForeignKeyConstraint(['settings_id'], ['site_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
