"""Add SiteSettings model

Revision ID: be867505cdc4
Revises: 
Create Date: 2026-09-16 18:17:55.417457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be867505cdc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_title', sa.String(length=200), nullable=False),
    sa.Column('site_subtitle', sa.String(length=300), nullable=True),
    sa.Column('site_description', sa.String(length=500), nullable=True),
    sa.Column('site_keywords', sa.String(length=300), nullable=True),
    sa.Column('show_header', sa.Boolean(), nullable=False),
    sa.Column('show_header_menu', sa.Boolean(), nullable=False),
    sa.Column('show_sidebar', sa.Boolean(), nullable=False),
    sa.Column('show_footer', sa.Boolean(), nullable=False),
    sa.Column('active_theme', sa.String(length=50), nullable=False),
    sa.Column('logo_file_id', sa.Integer(), nullable=True),
    sa.Column('favicon_file_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['favicon_file_id'], ['uploaded_file.id'], ),
    sa.ForeignKeyConstraint(['logo_file_id'], ['uploaded_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
