"""Add is_featured to Photo

Revision ID: e969af6d25af
Revises: be867505cdc4
Create Date: 2026-09-16 19:49:20.435857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e969af6d25af'
down_revision = 'be867505cdc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_photo_is_featured'), ['is_featured'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_is_featured'))
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
