"""Add thumbnail_name to UploadedFile

Revision ID: f4a4b38fec06
Revises: 923fa274a375
Create Date: 2026-09-19 12:45:21.545565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a4b38fec06'
down_revision = '923fa274a375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_name')

    # ### end Alembic commands ###
